# Generated by Django 4.0.6 on 2022-09-14 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funolympicgame2022', '0003_rename_news_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=30)),
                ('phone', models.CharField(default='', max_length=12)),
                ('email', models.CharField(default='', max_length=100)),
                ('message', models.TextField(default='', max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
