# Generated by Django 3.2 on 2022-09-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funolympicgame2022', '0004_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gamename', models.CharField(default='', max_length=30)),
                ('date', models.DateField(auto_now_add=True)),
                ('game', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
