# Generated by Django 4.0.6 on 2022-09-22 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_content_game'),
        ('funolympicgame2022', '0008_auto_20220918_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='gametype',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.gametype'),
        ),
    ]
