# Generated by Django 4.0.6 on 2022-09-27 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funolympicgame2022', '0009_new_gametype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new',
            old_name='newsp2',
            new_name='news',
        ),
        migrations.RemoveField(
            model_name='new',
            name='newsp1',
        ),
    ]
