# Generated by Django 4.0.6 on 2022-09-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funolympicgame2022', '0011_rename_img1_new_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='game1',
            field=models.CharField(default='', max_length=30),
        ),
    ]
