# Generated by Django 4.0.6 on 2022-09-27 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funolympicgame2022', '0012_alter_schedule_game1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='date',
            new_name='game_date',
        ),
    ]
