# Generated by Django 4.0.6 on 2022-09-27 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funolympicgame2022', '0013_rename_date_schedule_game_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='gamename',
            new_name='game_name',
        ),
    ]
