# Generated by Django 4.0.6 on 2022-09-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funolympicgame2022', '0015_alter_new_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='news2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='new',
            name='news',
            field=models.TextField(),
        ),
    ]
