# Generated by Django 4.0.6 on 2022-09-27 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_content_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='gametype',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.gametype'),
        ),
    ]
